version: '3.9'
services:
  web:
    image: checkmk/check-mk-raw:latest
    container_name: checkmk
    restart: always
    ports:
      - 8150:5000
      - 8100:8000
    networks:
      - default
    volumes:
      - ./monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
